# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
defaults:
  run:
    shell: cmd

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  Verification:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
    
      # Runs a single command using the runners shell
      - name: Run Code Analysis
        run: echo TODO

      # Runs a set of commands using the runners shell
      - name: Compile Code
        run: gcc first_week/Hello_World.c -o executable

      - name: Execute Code
        run: executable